apiVersion: batch/v1
kind: Job
metadata:
  name: demo
spec:
  template:
    spec:
      containers:
      - name: demo
        image: python
        command: ["python -v]
      restartPolicy: Never
  backoffLimit: 4
